## Importing the libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Product_ID": [
        "P001", "P002", "P003", "P004", "P005",
        "P006", "P007", "P008", "P009", "P010",
        "P011", "P012", "P013", "P014", "P015",
        "P016", "P017", "P018", "P019", "P020",
        "P020"
    ],

    "Product_Name": [
        "Laptop", "laptop", "SMARTPHONE", "Headphones", None,
        "keyboard", "Mouse", "Monitor", "USB Cable", "Power Bank",
        "Tablet", "Smart Watch", "Printer", "Desk Lamp",
        "External Hard Drive", "Webcam", "Laptop",
        "Bluetooth Speaker", "HDMI Cable", "Office Chair",
        "Office Chair"
    ],

    "Category": [
        "Electronics", "electronics", "ELECTRONICS", "Electronics",
        "electronics", "Computer Accessories", "computer accessories",
        "COMPUTER ACCESSORIES", "Accessories", "Accessories",
        "Electronics", "electronics", "Office Equipment",
        "Office Equipment", "Electronics", "Electronics", "electronics",
        "Audio", "Accessories", "Furniture", "Furniture"
    ],

    "Supplier": [
        "TechSource", "Tech Source", "MobileHub", "SoundPro",
        "TechSource", "KeyWorld", "Key World", "DisplayTech",
        "CablePro", "PowerPlus", "MobileHub", "MobileHub",
        "OfficeMax", "OfficeMax", "DataStore", "TechSource",
        "TechSource", "SoundPro", "Cable Pro", "FurniHouse",
        "FurniHouse"
    ],

    "Quantity": [
        12, 8, 25, "twenty", 18,
        5, -3, 7, 40, 22,
        6, 14, 4, 16, 3,
        9, 10, 11, 30, 2, 2
    ],

    "Unit_Price": [
        850000, 780000, 450000, 75000, 120000,
        45000, 18000, 150000, -5000, 35000,
        220000, 95000, 180000, 25000, 130000,
        65000, 850000, 60000, 12000, 95000, 95000
    ],

    "Reorder_Level": [
        10, 10, 15, 12, 8,
        10, 8, 5, 15, 20,
        8, 10, 6, 10, 5,
        6, 10, 8, 12, 5, 5
    ],

    "Last_Update": [
        "2025/01/10", "10-01-2025", "2025-01-12",
        "2025/01/15", "15/01/2025", "2025-01-18",
        "2025-01-20", "2025-01-21", "2025-01-22",
        "invalid-date", None, "2025-02-01",
        "2025-02-03", "2025-02-05", "2025-02-07",
        "2025-02-10", "2025/01/10", "2025-02-12",
        "2025-02-14", "2025-02-15", "2025-02-15"
    ]
}

In [4]:
df = pd.DataFrame(data)
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource,12,850000,10,2025/01/10
1,P002,laptop,electronics,Tech Source,8,780000,10,10-01-2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,25,450000,15,2025-01-12
3,P004,Headphones,Electronics,SoundPro,twenty,75000,12,2025/01/15
4,P005,NaN,electronics,TechSource,18,120000,8,15/01/2025
5,P006,keyboard,Computer Accessories,KeyWorld,5,45000,10,2025-01-18
6,P007,Mouse,computer accessories,Key World,-3,18000,8,2025-01-20
7,P008,Monitor,COMPUTER ACCESSORIES,DisplayTech,7,150000,5,2025-01-21
8,P009,USB Cable,Accessories,CablePro,40,-5000,15,2025-01-22
9,P010,Power Bank,Accessories,PowerPlus,22,35000,20,invalid-date
10,P011,Tablet,Electronics,MobileHub,6,220000,8,NaN
11,P012,Smart Watch,electronics,MobileHub,14,95000,10,2025-02-01
12,P013,Printer,Office Equipment,OfficeMax,4,180000,6,2025-02-03
13,P014,Desk Lamp,Office Equipment,OfficeMax,16,25000,10,2025-02-05
14,P015,External Hard Drive,Electronics,DataStore,3,130000,5,2025-02-07
15,P016,Webcam,Electronics,TechSource,9,65000,6,2025-02-10
16,P017,Laptop,electronics,TechSource,10,850000,10,2025/01/10
17,P018,Bluetooth Speaker,Audio,SoundPro,11,60000,8,2025-02-12
18,P019,HDMI Cable,Accessories,Cable Pro,30,12000,12,2025-02-14
19,P020,Office Chair,Furniture,FurniHouse,2,95000,5,2025-02-15
20,P020,Office Chair,Furniture,FurniHouse,2,95000,5,2025-02-15

## Inspect the Data

In [5]:
df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource,12,850000,10,2025/01/10
1,P002,laptop,electronics,Tech Source,8,780000,10,10-01-2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,25,450000,15,2025-01-12
3,P004,Headphones,Electronics,SoundPro,twenty,75000,12,2025/01/15
4,P005,NaN,electronics,TechSource,18,120000,8,15/01/2025

In [6]:
df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
16,P017,Laptop,electronics,TechSource,10,850000,10,2025/01/10
17,P018,Bluetooth Speaker,Audio,SoundPro,11,60000,8,2025-02-12
18,P019,HDMI Cable,Accessories,Cable Pro,30,12000,12,2025-02-14
19,P020,Office Chair,Furniture,FurniHouse,2,95000,5,2025-02-15
20,P020,Office Chair,Furniture,FurniHouse,2,95000,5,2025-02-15

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     21 non-null     str
 1   Product_Name   20 non-null     str
 2   Category       21 non-null     str
 3   Supplier       21 non-null     str
 4   Quantity       21 non-null     object
 5   Unit_Price     21 non-null     int64
 6   Reorder_Level  21 non-null     int64
 7   Last_Update    20 non-null     str
dtypes: int64(2), object(1), str(5)
memory usage: 1.4+ KB

In [8]:
df.describe()

          Unit_Price  Reorder_Level
count      21.000000      21.000000
mean   206904.761905       9.428571
std    277163.472478       3.867447
min     -5000.000000       5.000000
25%     45000.000000       6.000000
50%     95000.000000      10.000000
75%    180000.000000      10.000000
max    850000.000000      20.000000

In [9]:
# Find the missing values 
df.isnull().sum()

Product_ID       0
Product_Name     1
Category         0
Supplier         0
Quantity         0
Unit_Price       0
Reorder_Level    0
Last_Update      1
dtype: int64

In [10]:
# Number of Duplicate we have 
# df.duplicated().sum()
df[df.duplicated()]

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
20,P020,Office Chair,Furniture,FurniHouse,2,95000,5,2025-02-15

## Now Let The Cleaning Started

In [11]:
df["Product_Name"] = df["Product_Name"].str.title()
df["Category"] = df["Category"].str.title()
df["Supplier"] = df["Supplier"].str.lower()
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,techsource,12,850000,10,2025/01/10
1,P002,Laptop,Electronics,tech source,8,780000,10,10-01-2025
2,P003,Smartphone,Electronics,mobilehub,25,450000,15,2025-01-12
3,P004,Headphones,Electronics,soundpro,twenty,75000,12,2025/01/15
4,P005,NaN,Electronics,techsource,18,120000,8,15/01/2025
5,P006,Keyboard,Computer Accessories,keyworld,5,45000,10,2025-01-18
6,P007,Mouse,Computer Accessories,key world,-3,18000,8,2025-01-20
7,P008,Monitor,Computer Accessories,displaytech,7,150000,5,2025-01-21
8,P009,Usb Cable,Accessories,cablepro,40,-5000,15,2025-01-22
9,P010,Power Bank,Accessories,powerplus,22,35000,20,invalid-date
10,P011,Tablet,Electronics,mobilehub,6,220000,8,NaN
11,P012,Smart Watch,Electronics,mobilehub,14,95000,10,2025-02-01
12,P013,Printer,Office Equipment,officemax,4,180000,6,2025-02-03
13,P014,Desk Lamp,Office Equipment,officemax,16,25000,10,2025-02-05
14,P015,External Hard Drive,Electronics,datastore,3,130000,5,2025-02-07
15,P016,Webcam,Electronics,techsource,9,65000,6,2025-02-10
16,P017,Laptop,Electronics,techsource,10,850000,10,2025/01/10
17,P018,Bluetooth Speaker,Audio,soundpro,11,60000,8,2025-02-12
18,P019,Hdmi Cable,Accessories,cable pro,30,12000,12,2025-02-14
19,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15
20,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15

In [12]:
df["Supplier"] = df["Supplier"].replace({
    "tech source": "techsource",
    "key world": "keyworld",
    "cable pro": "cablepro"
})
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,techsource,12,850000,10,2025/01/10
1,P002,Laptop,Electronics,techsource,8,780000,10,10-01-2025
2,P003,Smartphone,Electronics,mobilehub,25,450000,15,2025-01-12
3,P004,Headphones,Electronics,soundpro,twenty,75000,12,2025/01/15
4,P005,NaN,Electronics,techsource,18,120000,8,15/01/2025
5,P006,Keyboard,Computer Accessories,keyworld,5,45000,10,2025-01-18
6,P007,Mouse,Computer Accessories,keyworld,-3,18000,8,2025-01-20
7,P008,Monitor,Computer Accessories,displaytech,7,150000,5,2025-01-21
8,P009,Usb Cable,Accessories,cablepro,40,-5000,15,2025-01-22
9,P010,Power Bank,Accessories,powerplus,22,35000,20,invalid-date
10,P011,Tablet,Electronics,mobilehub,6,220000,8,NaN
11,P012,Smart Watch,Electronics,mobilehub,14,95000,10,2025-02-01
12,P013,Printer,Office Equipment,officemax,4,180000,6,2025-02-03
13,P014,Desk Lamp,Office Equipment,officemax,16,25000,10,2025-02-05
14,P015,External Hard Drive,Electronics,datastore,3,130000,5,2025-02-07
15,P016,Webcam,Electronics,techsource,9,65000,6,2025-02-10
16,P017,Laptop,Electronics,techsource,10,850000,10,2025/01/10
17,P018,Bluetooth Speaker,Audio,soundpro,11,60000,8,2025-02-12
18,P019,Hdmi Cable,Accessories,cablepro,30,12000,12,2025-02-14
19,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15
20,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15

In [13]:
# df["Product_Name"].isnull().sum()

In [14]:
df["Product_Name"] = df["Product_Name"].fillna("Unknown Product")
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,techsource,12,850000,10,2025/01/10
1,P002,Laptop,Electronics,techsource,8,780000,10,10-01-2025
2,P003,Smartphone,Electronics,mobilehub,25,450000,15,2025-01-12
3,P004,Headphones,Electronics,soundpro,twenty,75000,12,2025/01/15
4,P005,Unknown Product,Electronics,techsource,18,120000,8,15/01/2025
5,P006,Keyboard,Computer Accessories,keyworld,5,45000,10,2025-01-18
6,P007,Mouse,Computer Accessories,keyworld,-3,18000,8,2025-01-20
7,P008,Monitor,Computer Accessories,displaytech,7,150000,5,2025-01-21
8,P009,Usb Cable,Accessories,cablepro,40,-5000,15,2025-01-22
9,P010,Power Bank,Accessories,powerplus,22,35000,20,invalid-date
10,P011,Tablet,Electronics,mobilehub,6,220000,8,NaN
11,P012,Smart Watch,Electronics,mobilehub,14,95000,10,2025-02-01
12,P013,Printer,Office Equipment,officemax,4,180000,6,2025-02-03
13,P014,Desk Lamp,Office Equipment,officemax,16,25000,10,2025-02-05
14,P015,External Hard Drive,Electronics,datastore,3,130000,5,2025-02-07
15,P016,Webcam,Electronics,techsource,9,65000,6,2025-02-10
16,P017,Laptop,Electronics,techsource,10,850000,10,2025/01/10
17,P018,Bluetooth Speaker,Audio,soundpro,11,60000,8,2025-02-12
18,P019,Hdmi Cable,Accessories,cablepro,30,12000,12,2025-02-14
19,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15
20,P020,Office Chair,Furniture,furnihouse,2,95000,5,2025-02-15

In [15]:
def clean_quantity(value):
    if value == "twenty":
        return 20
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan

df['Quantity'] = df["Quantity"].apply(clean_quantity)
df["Quantity"]

0     12
1      8
2     25
3     20
4     18
5      5
6     -3
7      7
8     40
9     22
10     6
11    14
12     4
13    16
14     3
15     9
16    10
17    11
18    30
19     2
20     2
Name: Quantity, dtype: int64

In [16]:
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")
df["Reorder_Level"] = pd.to_numeric(df["Reorder_Level"], errors="coerce")
# df["Unit_Price"].head()
# df["Reorder_Level"].head()
df.dtypes

Product_ID         str
Product_Name       str
Category           str
Supplier           str
Quantity         int64
Unit_Price       int64
Reorder_Level    int64
Last_Update        str
dtype: object

In [17]:
# Check the negative quantity
df[df["Quantity"] < 0]

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
6,P007,Mouse,Computer Accessories,keyworld,-3,18000,8,2025-01-20

In [18]:
df.loc[df["Quantity"] < 0, "Quantity"] = np.nan
# df["Quantity"]

In [19]:
df.loc[df["Unit_Price"] < 0, "Unit_Price"] = np.nan
# df["Unit_Price"]

## Fill the missing Numeric Value

In [20]:
# For Quantity
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df["Quantity"].head(7)

0    12.0
1     8.0
2    25.0
3    20.0
4    18.0
5     5.0
6    10.5
Name: Quantity, dtype: float64

In [21]:
# For Price
df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].median())
# df["Unit_Price"]

In [22]:
# df["Last_Update"]

In [23]:
from dateutil import parser

def clean_date(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT

df["Last_Update"] = df["Last_Update"].apply(clean_date)
df["Last_Update"]

0    2025-10-01
1    2025-01-10
2    2025-12-01
3    2025-01-15
4    2025-01-15
5    2025-01-18
6    2025-01-20
7    2025-01-21
8    2025-01-22
9           NaT
10          NaT
11   2025-01-02
12   2025-03-02
13   2025-05-02
14   2025-07-02
15   2025-10-02
16   2025-10-01
17   2025-12-02
18   2025-02-14
19   2025-02-15
20   2025-02-15
Name: Last_Update, dtype: datetime64[us]

In [24]:
median_date = df["Last_Update"].median()

df["Last_Update"] = df["Last_Update"].fillna(median_date)
df["Last_Update"]

0    2025-10-01
1    2025-01-10
2    2025-12-01
3    2025-01-15
4    2025-01-15
5    2025-01-18
6    2025-01-20
7    2025-01-21
8    2025-01-22
9    2025-02-15
10   2025-02-15
11   2025-01-02
12   2025-03-02
13   2025-05-02
14   2025-07-02
15   2025-10-02
16   2025-10-01
17   2025-12-02
18   2025-02-14
19   2025-02-15
20   2025-02-15
Name: Last_Update, dtype: datetime64[us]

In [25]:
df.isnull().sum()

Product_ID       0
Product_Name     0
Category         0
Supplier         0
Quantity         0
Unit_Price       0
Reorder_Level    0
Last_Update      0
dtype: int64

## Now handling the duplicate

In [26]:
df.duplicated().sum()

np.int64(1)

In [27]:
df = df.drop_duplicates()

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,techsource,12.0,850000.0,10,2025-10-01
1,P002,Laptop,Electronics,techsource,8.0,780000.0,10,2025-01-10
2,P003,Smartphone,Electronics,mobilehub,25.0,450000.0,15,2025-12-01
3,P004,Headphones,Electronics,soundpro,20.0,75000.0,12,2025-01-15
4,P005,Unknown Product,Electronics,techsource,18.0,120000.0,8,2025-01-15
5,P006,Keyboard,Computer Accessories,keyworld,5.0,45000.0,10,2025-01-18
6,P007,Mouse,Computer Accessories,keyworld,10.5,18000.0,8,2025-01-20
7,P008,Monitor,Computer Accessories,displaytech,7.0,150000.0,5,2025-01-21
8,P009,Usb Cable,Accessories,cablepro,40.0,95000.0,15,2025-01-22
9,P010,Power Bank,Accessories,powerplus,22.0,35000.0,20,2025-02-15
10,P011,Tablet,Electronics,mobilehub,6.0,220000.0,8,2025-02-15
11,P012,Smart Watch,Electronics,mobilehub,14.0,95000.0,10,2025-01-02
12,P013,Printer,Office Equipment,officemax,4.0,180000.0,6,2025-03-02
13,P014,Desk Lamp,Office Equipment,officemax,16.0,25000.0,10,2025-05-02
14,P015,External Hard Drive,Electronics,datastore,3.0,130000.0,5,2025-07-02
15,P016,Webcam,Electronics,techsource,9.0,65000.0,6,2025-10-02
16,P017,Laptop,Electronics,techsource,10.0,850000.0,10,2025-10-01
17,P018,Bluetooth Speaker,Audio,soundpro,11.0,60000.0,8,2025-12-02
18,P019,Hdmi Cable,Accessories,cablepro,30.0,12000.0,12,2025-02-14
19,P020,Office Chair,Furniture,furnihouse,2.0,95000.0,5,2025-02-15

## Now the Analysis of the Data

In [30]:
# product need restocking 
restock = df[df['Quantity'] < df["Reorder_Level"]]

In [31]:
restock

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
1,P002,Laptop,Electronics,techsource,8.0,780000.0,10,2025-01-10
5,P006,Keyboard,Computer Accessories,keyworld,5.0,45000.0,10,2025-01-18
10,P011,Tablet,Electronics,mobilehub,6.0,220000.0,8,2025-02-15
12,P013,Printer,Office Equipment,officemax,4.0,180000.0,6,2025-03-02
14,P015,External Hard Drive,Electronics,datastore,3.0,130000.0,5,2025-07-02
19,P020,Office Chair,Furniture,furnihouse,2.0,95000.0,5,2025-02-15

In [34]:
print("Products That need Restocking")
print(restock[["Product_ID", "Product_Name", "Quantity", "Reorder_Level", "Supplier"]])

Products That need Restocking
   Product_ID         Product_Name  Quantity  Reorder_Level    Supplier
1        P002               Laptop       8.0             10  techsource
5        P006             Keyboard       5.0             10    keyworld
10       P011               Tablet       6.0              8   mobilehub
12       P013              Printer       4.0              6   officemax
14       P015  External Hard Drive       3.0              5   datastore
19       P020         Office Chair       2.0              5  furnihouse

In [36]:
# The Average Unit price by category
average_price =df.groupby("Category")["Unit_Price"].mean().round(2).sort_values(ascending=False)
average_price

Category
Electronics             363500.00
Office Equipment        102500.00
Furniture                95000.00
Computer Accessories     71000.00
Audio                    60000.00
Accessories              47333.33
Name: Unit_Price, dtype: float64

In [37]:
# Supplier that provide the most product
supplier_counts = df["Supplier"].value_counts()
supplier_counts

Supplier
techsource     5
mobilehub      3
soundpro       2
keyworld       2
cablepro       2
officemax      2
displaytech    1
powerplus      1
datastore      1
furnihouse     1
Name: count, dtype: int64

In [42]:
top_supplier = supplier_counts.idxmax()
top_supplier_count = supplier_counts.max()

print(f"The supplier with the most product supply is {top_supplier} with the suppliers of {top_supplier_count}")

The supplier with the most product supply is techsource with the suppliers of 5

In [43]:
# Most expensive Product
top_5_expensive_prod = df.nlargest(5, "Unit_Price")
top_5_expensive_prod

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,techsource,12.0,850000.0,10,2025-10-01
16,P017,Laptop,Electronics,techsource,10.0,850000.0,10,2025-10-01
1,P002,Laptop,Electronics,techsource,8.0,780000.0,10,2025-01-10
2,P003,Smartphone,Electronics,mobilehub,25.0,450000.0,15,2025-12-01
10,P011,Tablet,Electronics,mobilehub,6.0,220000.0,8,2025-02-15

In [44]:
# sort by category and unit price
sorted_df = df.sort_values(["Category", "Unit_Price"], ascending=[True, False])
sorted_df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
8,P009,Usb Cable,Accessories,cablepro,40.0,95000.0,15,2025-01-22
9,P010,Power Bank,Accessories,powerplus,22.0,35000.0,20,2025-02-15
18,P019,Hdmi Cable,Accessories,cablepro,30.0,12000.0,12,2025-02-14
17,P018,Bluetooth Speaker,Audio,soundpro,11.0,60000.0,8,2025-12-02
7,P008,Monitor,Computer Accessories,displaytech,7.0,150000.0,5,2025-01-21
5,P006,Keyboard,Computer Accessories,keyworld,5.0,45000.0,10,2025-01-18
6,P007,Mouse,Computer Accessories,keyworld,10.5,18000.0,8,2025-01-20
0,P001,Laptop,Electronics,techsource,12.0,850000.0,10,2025-10-01
16,P017,Laptop,Electronics,techsource,10.0,850000.0,10,2025-10-01
1,P002,Laptop,Electronics,techsource,8.0,780000.0,10,2025-01-10
2,P003,Smartphone,Electronics,mobilehub,25.0,450000.0,15,2025-12-01
10,P011,Tablet,Electronics,mobilehub,6.0,220000.0,8,2025-02-15
14,P015,External Hard Drive,Electronics,datastore,3.0,130000.0,5,2025-07-02
4,P005,Unknown Product,Electronics,techsource,18.0,120000.0,8,2025-01-15
11,P012,Smart Watch,Electronics,mobilehub,14.0,95000.0,10,2025-01-02
3,P004,Headphones,Electronics,soundpro,20.0,75000.0,12,2025-01-15
15,P016,Webcam,Electronics,techsource,9.0,65000.0,6,2025-10-02
19,P020,Office Chair,Furniture,furnihouse,2.0,95000.0,5,2025-02-15
12,P013,Printer,Office Equipment,officemax,4.0,180000.0,6,2025-03-02
13,P014,Desk Lamp,Office Equipment,officemax,16.0,25000.0,10,2025-05-02

## Summary Of Insight

The analysis identified significant data quality issues in the original inventoy dataset used which include missing values, duplicate record, inconsistence capitalization negative quantities and prices and improperly formated date as well. These shows that the raw dataset is messy and can't be used for business analysis without cleaning or preprocessing it.
So after cleaning and standardizing the data, 7 products are identified to be below the reorder levels, these product represent immediate inventory replenishment priorites because if sales continues without restocking them it could later results to out of stocks
The supplier analysis identified that techsource as a supplier has the highest number of product records. Even though this might indicate a strong supplier relationship it also creates potential supplier concentration risk, if the business overly dependent on one supplier.
Electronics record the highest average unit price among the product categories. The most expensive product were also electronic products.

Overall, the analysis shows that the company's immmediate operational concern is inventory replenishment, while its broader data-management concern is data quality. The business should ensure validation rules for the product, quantities,prices, date, supplier and other of the product identifiers. Automated reorder alert will actully go a long way and also standardized supplier records will all reduced the likelihood of stock-out and improve the reliability of the future inventory reports